// Generated by @repo/design-tokens — do not edit.
// Source: packages/design-tokens/tokens/**

import SwiftUI

public extension Color {
    /// Fond des écrans.
    /// clair #F7F7F8 · sombre #0E0E10
    static let backgroundPrimary = Color(uiColor: UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 0.055, green: 0.055, blue: 0.063, alpha: 1)
            : UIColor(red: 0.969, green: 0.969, blue: 0.973, alpha: 1)
    })
    /// Cartes, modales et conteneurs posés sur le fond.
    /// clair #FFFFFF · sombre #18181B
    static let surfacePrimary = Color(uiColor: UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 0.094, green: 0.094, blue: 0.106, alpha: 1)
            : UIColor(red: 1, green: 1, blue: 1, alpha: 1)
    })
    /// Texte courant.
    /// clair #0E0E10 · sombre #EFEFF1
    static let textPrimary = Color(uiColor: UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 0.937, green: 0.937, blue: 0.945, alpha: 1)
            : UIColor(red: 0.055, green: 0.055, blue: 0.063, alpha: 1)
    })
    /// Texte secondaire et libellés de catégorie. Violet, comme text-muted dans la charte relevée.
    /// clair #5C16C5 · sombre #BF94FF
    static let textSecondary = Color(uiColor: UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 0.749, green: 0.58, blue: 1, alpha: 1)
            : UIColor(red: 0.361, green: 0.086, blue: 0.773, alpha: 1)
    })
    /// Accent du produit hors contexte de chaîne : liens, états actifs, boutons d'action (ADR 0019 §3).
    /// clair #5C16C5 · sombre #9147FF
    static let accentDefault = Color(uiColor: UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 0.569, green: 0.278, blue: 1, alpha: 1)
            : UIColor(red: 0.361, green: 0.086, blue: 0.773, alpha: 1)
    })
    /// Texte ou glyphe posé sur une surface d'accent (ADR 0019 §3).
    /// clair #FFFFFF · sombre #FFFFFF
    static let accentOnAccent = Color(uiColor: UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 1, green: 1, blue: 1, alpha: 1)
            : UIColor(red: 1, green: 1, blue: 1, alpha: 1)
    })
    /// Repli quand la couleur d'accent d'une chaîne est inutilisable (ADR 0019 §3).
    /// clair #5C16C5 · sombre #9147FF
    static let accentFallback = Color(uiColor: UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 0.569, green: 0.278, blue: 1, alpha: 1)
            : UIColor(red: 0.361, green: 0.086, blue: 0.773, alpha: 1)
    })

    /// Valeurs fixes par thème, réservées aux contextes sans traits et aux tests (ADR 0019 §2.2).
    enum Static {
        public static let backgroundPrimaryLight = Color(.sRGB, red: 0.969, green: 0.969, blue: 0.973, opacity: 1)
        public static let backgroundPrimaryDark = Color(.sRGB, red: 0.055, green: 0.055, blue: 0.063, opacity: 1)
        public static let surfacePrimaryLight = Color(.sRGB, red: 1, green: 1, blue: 1, opacity: 1)
        public static let surfacePrimaryDark = Color(.sRGB, red: 0.094, green: 0.094, blue: 0.106, opacity: 1)
        public static let textPrimaryLight = Color(.sRGB, red: 0.055, green: 0.055, blue: 0.063, opacity: 1)
        public static let textPrimaryDark = Color(.sRGB, red: 0.937, green: 0.937, blue: 0.945, opacity: 1)
        public static let textSecondaryLight = Color(.sRGB, red: 0.361, green: 0.086, blue: 0.773, opacity: 1)
        public static let textSecondaryDark = Color(.sRGB, red: 0.749, green: 0.58, blue: 1, opacity: 1)
        public static let accentDefaultLight = Color(.sRGB, red: 0.361, green: 0.086, blue: 0.773, opacity: 1)
        public static let accentDefaultDark = Color(.sRGB, red: 0.569, green: 0.278, blue: 1, opacity: 1)
        public static let accentOnAccentLight = Color(.sRGB, red: 1, green: 1, blue: 1, opacity: 1)
        public static let accentOnAccentDark = Color(.sRGB, red: 1, green: 1, blue: 1, opacity: 1)
        public static let accentFallbackLight = Color(.sRGB, red: 0.361, green: 0.086, blue: 0.773, opacity: 1)
        public static let accentFallbackDark = Color(.sRGB, red: 0.569, green: 0.278, blue: 1, opacity: 1)
    }
}
