// Generated by @repo/design-tokens — do not edit.
// Source: packages/design-tokens/tokens/**

import SwiftUI

public enum Radius {
    /// Charte relevée : rayon sm.
    public static let sm: CGFloat = 2
    /// Charte relevée : rayon md, cartes et vignettes.
    public static let md: CGFloat = 4
    /// Charte relevée : rayon lg.
    public static let lg: CGFloat = 6
    /// Charte relevée : rayon xl.
    public static let xl: CGFloat = 8
    /// Charte relevée : rayon pill, avatars et pastilles de catégorie.
    public static let pill: CGFloat = 9999
}
