// Generated by @repo/design-tokens — do not edit.
// Source: packages/design-tokens/tokens/**

import SwiftUI

public enum Spacing {
    /// 1 fois l'unité de base de la charte relevée (1 pt).
    public static let x1: CGFloat = 1
    /// 2 fois l'unité de base de la charte relevée (1 pt).
    public static let x2: CGFloat = 2
    /// 3 fois l'unité de base de la charte relevée (1 pt).
    public static let x3: CGFloat = 3
    /// 4 fois l'unité de base de la charte relevée (1 pt).
    public static let x4: CGFloat = 4
    /// 5 fois l'unité de base de la charte relevée (1 pt).
    public static let x5: CGFloat = 5
    /// 6 fois l'unité de base de la charte relevée (1 pt).
    public static let x6: CGFloat = 6
    /// 8 fois l'unité de base de la charte relevée (1 pt).
    public static let x8: CGFloat = 8
    /// 10 fois l'unité de base de la charte relevée (1 pt).
    public static let x10: CGFloat = 10
    /// 12 fois l'unité de base de la charte relevée (1 pt).
    public static let x12: CGFloat = 12
    /// 15 fois l'unité de base de la charte relevée (1 pt).
    public static let x15: CGFloat = 15
}
