// Generated by @repo/design-tokens — do not edit.
// Source: packages/design-tokens/tokens/**

import SwiftUI

public extension Font {
    /// Titres de section (display de la charte, 14 px / 600). Convention : text style iOS headline, pour le Dynamic Type.
    static let displayText = Font.headline.weight(.semibold)
    /// Titres de carte et sous-sections (heading de la charte, 13 px / 600). Convention : text style iOS subheadline.
    static let headingText = Font.subheadline.weight(.semibold)
    /// Texte courant, titres de stream, métadonnées (body de la charte, 12 px / 600). Convention : text style iOS footnote.
    static let bodyText = Font.footnote.weight(.semibold)
}
