import { describe, expect, it } from "vitest";

import { formatThemedColors, type DesignToken } from "./swift.ts";

const colorToken = (overrides: Partial<DesignToken> = {}): DesignToken => ({
  path: ["color", "background", "primary"],
  $type: "color",
  value: "#ffffff",
  ...overrides,
});

const themes = ({
  light = [colorToken()],
  dark = [colorToken({ value: "#0e0e10" })],
}: {
  readonly light?: readonly DesignToken[];
  readonly dark?: readonly DesignToken[];
} = {}) => ({ light, dark });

const SWIFT_RESERVED_KEYWORDS = [
  "associatedtype",
  "class",
  "default",
  "deinit",
  "enum",
  "extension",
  "fileprivate",
  "func",
  "import",
  "init",
  "inout",
  "internal",
  "let",
  "operator",
  "private",
  "protocol",
  "public",
  "repeat",
  "rethrows",
  "static",
  "struct",
  "subscript",
  "typealias",
  "var",
  "where",
  "while",
  "case",
  "break",
  "continue",
  "defer",
  "do",
  "else",
  "fallthrough",
  "for",
  "guard",
  "if",
  "in",
  "return",
  "switch",
  "catch",
  "throw",
  "throws",
  "try",
  "as",
  "is",
  "nil",
  "self",
  "super",
  "true",
  "false",
];

describe("formatThemedColors", () => {
  it("generates the complete Swift file for a single role", () => {
    const output = formatThemedColors(themes());

    expect(output).toBe(
      [
        "// Generated by @repo/design-tokens — do not edit.",
        "// Source: packages/design-tokens/tokens/**",
        "",
        "import SwiftUI",
        "",
        "public extension Color {",
        "    /// clair #FFFFFF · sombre #0E0E10",
        "    static let backgroundPrimary = Color(uiColor: UIColor { trait in",
        "        trait.userInterfaceStyle == .dark",
        "            ? UIColor(red: 0.055, green: 0.055, blue: 0.063, alpha: 1)",
        "            : UIColor(red: 1, green: 1, blue: 1, alpha: 1)",
        "    })",
        "",
        "    /// Valeurs fixes par thème, réservées aux contextes sans traits et aux tests (ADR 0019 §2.2).",
        "    enum Static {",
        "        public static let backgroundPrimaryLight = Color(.sRGB, red: 1, green: 1, blue: 1, opacity: 1)",
        "        public static let backgroundPrimaryDark = Color(.sRGB, red: 0.055, green: 0.055, blue: 0.063, opacity: 1)",
        "    }",
        "}",
        "",
      ].join("\n"),
    );
  });

  it("camel-cases every segment after the category", () => {
    const path = ["color", "accent", "on", "accent"];
    const output = formatThemedColors(
      themes({ light: [colorToken({ path })], dark: [colorToken({ path })] }),
    );

    expect(output).toContain("static let accentOnAccent =");
  });

  it("accepts digits after the first character of a role name", () => {
    const path = ["color", "chatUsername", "3"];
    const output = formatThemedColors(
      themes({ light: [colorToken({ path })], dark: [colorToken({ path })] }),
    );

    expect(output).toContain("static let chatUsername3 =");
  });

  it.each(SWIFT_RESERVED_KEYWORDS)(
    "fails on a role named after the Swift keyword %s",
    (keyword) => {
      const path = ["color", keyword];

      expect(() =>
        formatThemedColors({
          light: [colorToken({ path })],
          dark: [colorToken({ path })],
        }),
      ).toThrowError(new RegExp(`"${keyword}", a reserved Swift keyword`));
    },
  );

  it("fails on a 7-digit hex", () => {
    const light = [colorToken({ value: "#fffffff" })];

    expect(() => formatThemedColors(themes({ light }))).toThrowError(
      /not a 6- or 8-digit hex/,
    );
  });

  it("fails on a hex colour preceded by other characters", () => {
    const light = [colorToken({ value: "a#ffffff" })];

    expect(() => formatThemedColors(themes({ light }))).toThrowError(
      /not a 6- or 8-digit hex/,
    );
  });

  it("fails on a non-string value that would stringify to a hex colour", () => {
    const light = [colorToken({ value: ["#ffffff"] })];

    expect(() => formatThemedColors(themes({ light }))).toThrowError(
      /not a 6- or 8-digit hex/,
    );
  });

  it("lists every missing role at once, separated", () => {
    const light = [
      colorToken(),
      colorToken({ path: ["color", "text", "primary"] }),
    ];
    const dark = [
      colorToken({ value: "#0e0e10" }),
      colorToken({ path: ["color", "accent", "default"] }),
    ];

    expect(() => formatThemedColors({ light, dark })).toThrowError(
      '"color.text.primary" is missing in the dark theme; "color.accent.default" is missing in the light theme.',
    );
  });

  it("emits one dynamic colour per role, resolved by the trait collection", () => {
    const output = formatThemedColors(themes());

    expect(output).toContain("public extension Color {");
    expect(output).toContain(
      [
        "    static let backgroundPrimary = Color(uiColor: UIColor { trait in",
        "        trait.userInterfaceStyle == .dark",
        "            ? UIColor(red: 0.055, green: 0.055, blue: 0.063, alpha: 1)",
        "            : UIColor(red: 1, green: 1, blue: 1, alpha: 1)",
        "    })",
      ].join("\n"),
    );
  });

  it("documents both theme values above the role", () => {
    const output = formatThemedColors(themes());

    expect(output).toContain("    /// clair #FFFFFF · sombre #0E0E10");
  });

  it("puts the role description before the theme values", () => {
    const output = formatThemedColors(
      themes({
        light: [colorToken({ comment: "Fond des écrans." })],
        dark: [colorToken({ value: "#0e0e10", comment: "Fond des écrans." })],
      }),
    );

    expect(output).toContain(
      [
        "    /// Fond des écrans.",
        "    /// clair #FFFFFF · sombre #0E0E10",
      ].join("\n"),
    );
  });

  it("exposes both static values under Color.Static for trait-less contexts", () => {
    const output = formatThemedColors(themes());

    expect(output).toContain("    enum Static {");
    expect(output).toContain(
      "        public static let backgroundPrimaryLight = Color(.sRGB, red: 1, green: 1, blue: 1, opacity: 1)",
    );
    expect(output).toContain(
      "        public static let backgroundPrimaryDark = Color(.sRGB, red: 0.055, green: 0.055, blue: 0.063, opacity: 1)",
    );
  });

  it("keeps every role, in declaration order", () => {
    const light = [
      colorToken(),
      colorToken({ path: ["color", "text", "primary"], value: "#0e0e10" }),
    ];
    const dark = [
      colorToken({ value: "#0e0e10" }),
      colorToken({ path: ["color", "text", "primary"], value: "#efeff1" }),
    ];
    const output = formatThemedColors({ light, dark });

    expect(output.indexOf("static let backgroundPrimary =")).toBeGreaterThan(
      -1,
    );
    expect(output.indexOf("static let textPrimary =")).toBeGreaterThan(
      output.indexOf("static let backgroundPrimary ="),
    );
  });

  it("pairs roles by path, not by position", () => {
    const light = [
      colorToken(),
      colorToken({ path: ["color", "text", "primary"], value: "#0e0e10" }),
    ];
    const dark = [
      colorToken({ path: ["color", "text", "primary"], value: "#efeff1" }),
      colorToken({ value: "#18181b" }),
    ];
    const output = formatThemedColors({ light, dark });

    expect(output).toContain("    /// clair #0E0E10 · sombre #EFEFF1");
    expect(output).toContain("    /// clair #FFFFFF · sombre #18181B");
  });

  it("reads the alpha channel of an 8-digit hex", () => {
    const output = formatThemedColors(
      themes({
        light: [colorToken({ value: "#00000099" })],
        dark: [colorToken({ value: "#ffffff99" })],
      }),
    );

    expect(output).toContain(
      "            : UIColor(red: 0, green: 0, blue: 0, alpha: 0.6)",
    );
    expect(output).toContain(
      "            ? UIColor(red: 1, green: 1, blue: 1, alpha: 0.6)",
    );
  });

  it("fails when a role exists in the light theme only, naming the path and the theme", () => {
    const light = [
      colorToken(),
      colorToken({ path: ["color", "text", "primary"] }),
    ];

    expect(() => formatThemedColors(themes({ light }))).toThrowError(
      /color\.text\.primary.*dark/,
    );
  });

  it("fails when a role exists in the dark theme only, naming the path and the theme", () => {
    const dark = [
      colorToken({ value: "#0e0e10" }),
      colorToken({ path: ["color", "accent", "default"] }),
    ];

    expect(() => formatThemedColors(themes({ dark }))).toThrowError(
      /color\.accent\.default.*light/,
    );
  });

  it("fails on an unresolved alias", () => {
    const dark = [colorToken({ value: "{core.color.neutral.5}" })];

    expect(() => formatThemedColors(themes({ dark }))).toThrowError(
      /Unresolved alias.*color\.background\.primary/,
    );
  });

  it("fails on a value that is not a 6- or 8-digit hex colour", () => {
    const light = [colorToken({ value: "#fff" })];

    expect(() => formatThemedColors(themes({ light }))).toThrowError(
      /color\.background\.primary.*#fff/,
    );
  });

  it("fails on a non-string value", () => {
    const light = [colorToken({ value: 42 })];

    expect(() => formatThemedColors(themes({ light }))).toThrowError(
      /not a 6- or 8-digit hex/,
    );
  });

  it("fails on a role whose Swift name would be a reserved keyword", () => {
    const light = [colorToken({ path: ["color", "default"] })];
    const dark = [colorToken({ path: ["color", "default"] })];

    expect(() => formatThemedColors({ light, dark })).toThrowError(/reserved/i);
  });

  it("fails on a role whose Swift name would start with a digit", () => {
    const light = [colorToken({ path: ["color", "2xl"] })];
    const dark = [colorToken({ path: ["color", "2xl"] })];

    expect(() => formatThemedColors({ light, dark })).toThrowError(
      /not a valid Swift identifier/,
    );
  });

  it("fails on a role with no segment left once its category is dropped", () => {
    const light = [colorToken({ path: ["color"] })];
    const dark = [colorToken({ path: ["color"] })];

    expect(() => formatThemedColors({ light, dark })).toThrowError(
      /no segment left/,
    );
  });
});
