import { parseHexColor } from "../color/hex.ts";

export type DesignToken = {
  readonly path: readonly string[];
  readonly $type: string;
  readonly value: unknown;
  readonly comment?: string;
};

export type ThemedTokens = {
  readonly light: readonly DesignToken[];
  readonly dark: readonly DesignToken[];
};

const GENERATED_HEADER = [
  "// Generated by @repo/design-tokens — do not edit.",
  "// Source: packages/design-tokens/tokens/**",
  "",
  "import SwiftUI",
  "",
].join("\n");

const SWIFT_KEYWORDS = new Set([
  "associatedtype",
  "class",
  "default",
  "deinit",
  "enum",
  "extension",
  "fileprivate",
  "func",
  "import",
  "init",
  "inout",
  "internal",
  "let",
  "operator",
  "private",
  "protocol",
  "public",
  "repeat",
  "rethrows",
  "static",
  "struct",
  "subscript",
  "typealias",
  "var",
  "where",
  "while",
  "case",
  "break",
  "continue",
  "defer",
  "do",
  "else",
  "fallthrough",
  "for",
  "guard",
  "if",
  "in",
  "return",
  "switch",
  "catch",
  "throw",
  "throws",
  "try",
  "as",
  "is",
  "nil",
  "self",
  "super",
  "true",
  "false",
]);

const tokenId = (path: readonly string[]): string => path.join(".");

const swiftMemberName = (path: readonly string[]): string => {
  const [, ...segments] = path;

  if (segments.length === 0) {
    throw new Error(
      `Token "${tokenId(path)}" has no segment left once its category is dropped.`,
    );
  }

  const [head, ...tail] = segments as [string, ...string[]];
  const name =
    head.charAt(0).toLowerCase() +
    head.slice(1) +
    tail.map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join("");

  if (/^[0-9]/.test(name)) {
    throw new Error(
      `Token "${tokenId(path)}" maps to "${name}", which is not a valid Swift identifier.`,
    );
  }

  if (SWIFT_KEYWORDS.has(name)) {
    throw new Error(
      `Token "${tokenId(path)}" maps to "${name}", a reserved Swift keyword.`,
    );
  }

  return name;
};

const assertResolved = (value: unknown, path: readonly string[]): void => {
  if (typeof value === "string" && value.includes("{")) {
    throw new Error(`Unresolved alias for token "${tokenId(path)}": ${value}.`);
  }
};

type SRGB = {
  readonly hex: string;
  readonly red: string;
  readonly green: string;
  readonly blue: string;
  readonly opacity: string;
};

const roundChannel = (value: number): string =>
  String(Number(value.toFixed(3)));

const toSRGB = (value: unknown, path: readonly string[]): SRGB => {
  assertResolved(value, path);

  const color = parseHexColor(value);

  if (color === undefined) {
    throw new Error(
      `Token "${tokenId(path)}" is not a 6- or 8-digit hex colour: ${String(value)}.`,
    );
  }

  const unit = (channel: number): string => roundChannel(channel / 255);

  return {
    hex: color.hex,
    red: unit(color.red),
    green: unit(color.green),
    blue: unit(color.blue),
    opacity: color.alpha === undefined ? "1" : unit(color.alpha),
  };
};

const docComment = (comment: string | undefined): readonly string[] =>
  comment === undefined ? [] : [`    /// ${comment}`];

const uiColor = ({ red, green, blue, opacity }: SRGB): string =>
  `UIColor(red: ${red}, green: ${green}, blue: ${blue}, alpha: ${opacity})`;

const staticColor = ({ red, green, blue, opacity }: SRGB): string =>
  `Color(.sRGB, red: ${red}, green: ${green}, blue: ${blue}, opacity: ${opacity})`;

const missingRoles = (
  from: readonly DesignToken[],
  to: ReadonlyMap<string, DesignToken>,
  { missingIn }: { readonly missingIn: string },
): readonly string[] =>
  from
    .filter((token) => !to.has(tokenId(token.path)))
    .map(
      (token) =>
        `"${tokenId(token.path)}" is missing in the ${missingIn} theme`,
    );

const pairRoles = ({ light, dark }: ThemedTokens) => {
  const darkByPath = new Map(dark.map((token) => [tokenId(token.path), token]));
  const lightByPath = new Map(
    light.map((token) => [tokenId(token.path), token]),
  );
  const errors = [
    ...missingRoles(light, darkByPath, { missingIn: "dark" }),
    ...missingRoles(dark, lightByPath, { missingIn: "light" }),
  ];

  if (errors.length > 0) {
    throw new Error(
      `Themes are not structurally identical: ${errors.join("; ")}.`,
    );
  }

  return light.map((lightToken) => ({
    lightToken,
    darkToken: darkByPath.get(tokenId(lightToken.path)) as DesignToken,
  }));
};

export const formatThemedColors = (themes: ThemedTokens): string => {
  const roles = pairRoles(themes).map(({ lightToken, darkToken }) => ({
    name: swiftMemberName(lightToken.path),
    comment: lightToken.comment,
    light: toSRGB(lightToken.value, lightToken.path),
    dark: toSRGB(darkToken.value, darkToken.path),
  }));

  const dynamicMembers = roles.flatMap(({ name, comment, light, dark }) => [
    ...docComment(comment),
    `    /// clair ${light.hex} · sombre ${dark.hex}`,
    `    static let ${name} = Color(uiColor: UIColor { trait in`,
    "        trait.userInterfaceStyle == .dark",
    `            ? ${uiColor(dark)}`,
    `            : ${uiColor(light)}`,
    "    })",
  ]);

  const staticMembers = roles.flatMap(({ name, light, dark }) => [
    `        public static let ${name}Light = ${staticColor(light)}`,
    `        public static let ${name}Dark = ${staticColor(dark)}`,
  ]);

  return [
    GENERATED_HEADER,
    "public extension Color {",
    ...dynamicMembers,
    "",
    "    /// Valeurs fixes par thème, réservées aux contextes sans traits et aux tests (ADR 0019 §2.2).",
    "    enum Static {",
    ...staticMembers,
    "    }",
    "}",
    "",
  ].join("\n");
};
