import { parseHexColor } from "../color/hex.ts";

export type DesignToken = {
  readonly path: readonly string[];
  readonly $type: string;
  readonly value: unknown;
  readonly comment?: string;
};

export type ThemedTokens = {
  readonly light: readonly DesignToken[];
  readonly dark: readonly DesignToken[];
};

const GENERATED_HEADER = [
  "// Generated by @repo/design-tokens — do not edit.",
  "// Source: packages/design-tokens/tokens/**",
  "",
  "import SwiftUI",
  "",
].join("\n");

const SWIFT_KEYWORDS = new Set([
  "associatedtype",
  "class",
  "default",
  "deinit",
  "enum",
  "extension",
  "fileprivate",
  "func",
  "import",
  "init",
  "inout",
  "internal",
  "let",
  "operator",
  "private",
  "protocol",
  "public",
  "repeat",
  "rethrows",
  "static",
  "struct",
  "subscript",
  "typealias",
  "var",
  "where",
  "while",
  "case",
  "break",
  "continue",
  "defer",
  "do",
  "else",
  "fallthrough",
  "for",
  "guard",
  "if",
  "in",
  "return",
  "switch",
  "catch",
  "throw",
  "throws",
  "try",
  "as",
  "is",
  "nil",
  "self",
  "super",
  "true",
  "false",
]);

const tokenId = (path: readonly string[]): string => path.join(".");

const swiftMemberName = (path: readonly string[]): string => {
  const [, head, ...tail] = path;

  if (head === undefined) {
    throw new Error(`Token "${tokenId(path)}" has no segment left once its category is dropped.`);
  }

  const name =
    head.charAt(0).toLowerCase() +
    head.slice(1) +
    tail.map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join("");

  if (/^[0-9]/.test(name)) {
    throw new Error(
      `Token "${tokenId(path)}" maps to "${name}", which is not a valid Swift identifier.`,
    );
  }

  if (SWIFT_KEYWORDS.has(name)) {
    throw new Error(`Token "${tokenId(path)}" maps to "${name}", a reserved Swift keyword.`);
  }

  return name;
};

const assertResolved = (value: unknown, path: readonly string[]): void => {
  if (typeof value === "string" && value.includes("{")) {
    throw new Error(`Unresolved alias for token "${tokenId(path)}": ${value}.`);
  }
};

type SRGB = {
  readonly hex: string;
  readonly red: string;
  readonly green: string;
  readonly blue: string;
  readonly opacity: string;
};

const roundChannel = (value: number): string => String(Number(value.toFixed(3)));

const unit = (channel: number): string => roundChannel(channel / 255);

const toSRGB = (value: unknown, path: readonly string[]): SRGB => {
  assertResolved(value, path);

  const color = parseHexColor(value);

  if (color === undefined) {
    throw new Error(
      `Token "${tokenId(path)}" is not a 6- or 8-digit hex colour: ${String(value)}.`,
    );
  }

  return {
    hex: color.hex,
    red: unit(color.red),
    green: unit(color.green),
    blue: unit(color.blue),
    opacity: color.alpha === undefined ? "1" : unit(color.alpha),
  };
};

const docComment = (comment: string | undefined): readonly string[] =>
  comment === undefined ? [] : [`    /// ${comment}`];

const uiColor = ({ red, green, blue, opacity }: SRGB): string =>
  `UIColor(red: ${red}, green: ${green}, blue: ${blue}, alpha: ${opacity})`;

const staticColor = ({ red, green, blue, opacity }: SRGB): string =>
  `Color(.sRGB, red: ${red}, green: ${green}, blue: ${blue}, opacity: ${opacity})`;

const missingRoles = (
  from: readonly DesignToken[],
  to: ReadonlyMap<string, DesignToken>,
  { missingIn }: { readonly missingIn: string },
): readonly string[] =>
  from
    .filter((token) => !to.has(tokenId(token.path)))
    .map((token) => `"${tokenId(token.path)}" is missing in the ${missingIn} theme`);

const pairRoles = ({ light, dark }: ThemedTokens) => {
  const darkByPath = new Map(dark.map((token) => [tokenId(token.path), token]));
  const lightByPath = new Map(light.map((token) => [tokenId(token.path), token]));
  const errors = [
    ...missingRoles(light, darkByPath, { missingIn: "dark" }),
    ...missingRoles(dark, lightByPath, { missingIn: "light" }),
  ];

  if (errors.length > 0) {
    throw new Error(`Themes are not structurally identical: ${errors.join("; ")}.`);
  }

  return light.flatMap((lightToken) => {
    const darkToken = darkByPath.get(tokenId(lightToken.path));

    return darkToken === undefined ? [] : [{ lightToken, darkToken }];
  });
};

export const formatThemedColors = (themes: ThemedTokens): string => {
  const roles = pairRoles(themes).map(({ lightToken, darkToken }) => ({
    name: swiftMemberName(lightToken.path),
    comment: lightToken.comment,
    light: toSRGB(lightToken.value, lightToken.path),
    dark: toSRGB(darkToken.value, darkToken.path),
  }));

  const dynamicMembers = roles.flatMap(({ name, comment, light, dark }) => [
    ...docComment(comment),
    `    /// clair ${light.hex} · sombre ${dark.hex}`,
    `    static let ${name} = Color(uiColor: UIColor { trait in`,
    "        trait.userInterfaceStyle == .dark",
    `            ? ${uiColor(dark)}`,
    `            : ${uiColor(light)}`,
    "    })",
  ]);

  const staticMembers = roles.flatMap(({ name, light, dark }) => [
    `        public static let ${name}Light = ${staticColor(light)}`,
    `        public static let ${name}Dark = ${staticColor(dark)}`,
  ]);

  return [
    GENERATED_HEADER,
    "public extension Color {",
    ...dynamicMembers,
    "",
    "    /// Valeurs fixes par thème, réservées aux contextes sans traits et aux tests (ADR 0019 §2.2).",
    "    enum Static {",
    ...staticMembers,
    "    }",
    "}",
    "",
  ].join("\n");
};

const toPoints = (value: unknown, path: readonly string[]): string => {
  assertResolved(value, path);

  if (typeof value === "number") {
    return String(value);
  }

  const points = typeof value === "string" ? /^(-?[0-9]+(\.[0-9]+)?)(px)?$/.exec(value) : null;

  if (points === null) {
    throw new Error(`Token "${tokenId(path)}" is not a pixel dimension: ${String(value)}.`);
  }

  return String(Number(points[1]));
};

export const formatDimensions = (
  tokens: readonly DesignToken[],
  { namespace }: { readonly namespace: string },
): string => {
  const members = tokens.flatMap((token) => [
    ...docComment(token.comment),
    `    public static let ${swiftMemberName(token.path)}: CGFloat = ${toPoints(token.value, token.path)}`,
  ]);

  return [GENERATED_HEADER, `public enum ${namespace} {`, ...members, "}", ""].join("\n");
};

const IOS_TEXT_STYLES = new Set([
  "largeTitle",
  "title",
  "title2",
  "title3",
  "headline",
  "subheadline",
  "body",
  "callout",
  "footnote",
  "caption",
  "caption2",
]);

const FONT_WEIGHTS = new Map<number, string>([
  [100, "ultraLight"],
  [200, "thin"],
  [300, "light"],
  [400, "regular"],
  [500, "medium"],
  [600, "semibold"],
  [700, "bold"],
  [800, "heavy"],
  [900, "black"],
]);

type TextStyleValue = {
  readonly textStyle: string;
  readonly fontWeight?: unknown;
};

const asTextStyle = (value: unknown, path: readonly string[]): TextStyleValue => {
  assertResolved(value, path);

  if (
    typeof value !== "object" ||
    value === null ||
    !("textStyle" in value) ||
    typeof value.textStyle !== "string"
  ) {
    throw new Error(`Token "${tokenId(path)}" is not an iOS text style value.`);
  }

  const { textStyle } = value;

  if (!IOS_TEXT_STYLES.has(textStyle)) {
    throw new Error(
      `Token "${tokenId(path)}" uses "${textStyle}", which SwiftUI does not provide as a text style.`,
    );
  }

  return { ...value, textStyle };
};

const toFontWeight = (value: unknown, path: readonly string[]): string => {
  const weight = FONT_WEIGHTS.get(Number(value));

  if (weight === undefined) {
    throw new Error(`Token "${tokenId(path)}" uses the unsupported font weight ${String(value)}.`);
  }

  return weight;
};

export const formatTextStyles = (tokens: readonly DesignToken[]): string => {
  const members = tokens.flatMap((token) => {
    const { textStyle, fontWeight } = asTextStyle(token.value, token.path);
    const name = swiftMemberName(token.path);

    if (IOS_TEXT_STYLES.has(name)) {
      throw new Error(
        `Token "${tokenId(token.path)}" maps to "${name}", which would shadow the SwiftUI Font member of the same name.`,
      );
    }

    const weight =
      fontWeight === undefined ? "" : `.weight(.${toFontWeight(fontWeight, token.path)})`;

    return [...docComment(token.comment), `    static let ${name} = Font.${textStyle}${weight}`];
  });

  return [GENERATED_HEADER, "public extension Font {", ...members, "}", ""].join("\n");
};
