import { describe, expect, it } from "vitest";

import {
  formatDimensions,
  formatTextStyles,
  type DesignToken,
} from "./swift.ts";

const textStyleToken = (overrides: Partial<DesignToken> = {}): DesignToken => ({
  path: ["typography", "bodyText"],
  $type: "iosTextStyle",
  value: { textStyle: "footnote", fontWeight: 600 },
  ...overrides,
});

const dimensionToken = (overrides: Partial<DesignToken> = {}): DesignToken => ({
  path: ["spacing", "x8"],
  $type: "dimension",
  value: "8px",
  ...overrides,
});

const HEADER = [
  "// Generated by @repo/design-tokens — do not edit.",
  "// Source: packages/design-tokens/tokens/**",
  "",
  "import SwiftUI",
  "",
];

const SWIFTUI_TEXT_STYLES = [
  "largeTitle",
  "title",
  "title2",
  "title3",
  "headline",
  "subheadline",
  "body",
  "callout",
  "footnote",
  "caption",
  "caption2",
];

describe("formatTextStyles", () => {
  it("generates the complete Swift file, mapping a token to a system text style and a weight", () => {
    const output = formatTextStyles([
      textStyleToken({ comment: "Texte courant." }),
    ]);

    expect(output).toBe(
      [
        ...HEADER,
        "public extension Font {",
        "    /// Texte courant.",
        "    static let bodyText = Font.footnote.weight(.semibold)",
        "}",
        "",
      ].join("\n"),
    );
  });

  it.each([
    [100, "ultraLight"],
    [200, "thin"],
    [300, "light"],
    [400, "regular"],
    [500, "medium"],
    [600, "semibold"],
    [700, "bold"],
    [800, "heavy"],
    [900, "black"],
  ])("maps the CSS weight %i to .%s", (fontWeight, swiftWeight) => {
    const output = formatTextStyles([
      textStyleToken({ value: { textStyle: "body", fontWeight } }),
    ]);

    expect(output).toContain(
      `static let bodyText = Font.body.weight(.${swiftWeight})`,
    );
  });

  it("keeps the system weight when the token declares none", () => {
    const output = formatTextStyles([
      textStyleToken({ value: { textStyle: "headline" } }),
    ]);

    expect(output).toContain("    static let bodyText = Font.headline\n");
  });

  it.each(SWIFTUI_TEXT_STYLES)(
    "accepts the SwiftUI text style %s",
    (textStyle) => {
      const output = formatTextStyles([
        textStyleToken({ value: { textStyle } }),
      ]);

      expect(output).toContain(`static let bodyText = Font.${textStyle}`);
    },
  );

  it("omits the doc comment when the token has no description", () => {
    const output = formatTextStyles([textStyleToken()]);

    expect(output).toContain(
      ["public extension Font {", "    static let bodyText ="].join("\n"),
    );
  });

  it.each(SWIFTUI_TEXT_STYLES)(
    "refuses a token named %s, which would shadow the SwiftUI Font member",
    (name) => {
      expect(() =>
        formatTextStyles([textStyleToken({ path: ["typography", name] })]),
      ).toThrowError(
        new RegExp(`"${name}", which would shadow the SwiftUI Font member`),
      );
    },
  );

  it("refuses a text style SwiftUI does not provide", () => {
    expect(() =>
      formatTextStyles([
        textStyleToken({ value: { textStyle: "display", fontWeight: 600 } }),
      ]),
    ).toThrowError(/"display", which SwiftUI does not provide/);
  });

  it("refuses an unsupported font weight", () => {
    expect(() =>
      formatTextStyles([
        textStyleToken({ value: { textStyle: "body", fontWeight: 650 } }),
      ]),
    ).toThrowError(/unsupported font weight 650/);
  });

  it.each([
    ["a pixel size", "12px"],
    ["null", null],
    ["an object without a text style", { fontWeight: 600 }],
  ])("refuses %s as a text style value", (_label, value) => {
    expect(() => formatTextStyles([textStyleToken({ value })])).toThrowError(
      /typography\.bodyText.*not an iOS text style value/,
    );
  });

  it("refuses an unresolved alias", () => {
    expect(() =>
      formatTextStyles([textStyleToken({ value: "{typography.base}" })]),
    ).toThrowError(/Unresolved alias.*typography\.bodyText/);
  });
});

describe("formatDimensions", () => {
  it("generates the complete Swift file, as CGFloat points in a namespace", () => {
    const output = formatDimensions(
      [dimensionToken({ comment: "Charte relevée." })],
      {
        namespace: "Spacing",
      },
    );

    expect(output).toBe(
      [
        ...HEADER,
        "public enum Spacing {",
        "    /// Charte relevée.",
        "    public static let x8: CGFloat = 8",
        "}",
        "",
      ].join("\n"),
    );
  });

  it.each([
    ["a px dimension", "15px", "15"],
    ["a unitless string", "4", "4"],
    ["a number", 9999, "9999"],
    ["a decimal", "0.5px", "0.5"],
    ["a decimal with several digits", "0.25px", "0.25"],
    ["a negative value", "-2px", "-2"],
  ])("reads %s", (_label, value, points) => {
    const output = formatDimensions([dimensionToken({ value })], {
      namespace: "Radius",
    });

    expect(output).toContain(`    public static let x8: CGFloat = ${points}\n`);
  });

  it("omits the doc comment when the token has no description", () => {
    const output = formatDimensions([dimensionToken()], {
      namespace: "Spacing",
    });

    expect(output).toContain(
      ["public enum Spacing {", "    public static let x8"].join("\n"),
    );
  });

  it.each([
    ["a rem value", "1rem"],
    ["a value with trailing garbage", "8pxx"],
    ["a value with leading garbage", "a8px"],
    ["a dangling decimal point", "8.px"],
    ["an object", { value: 8 }],
    ["a non-string value that would stringify to a dimension", ["8px"]],
  ])("refuses %s", (_label, value) => {
    expect(() =>
      formatDimensions([dimensionToken({ value })], { namespace: "Spacing" }),
    ).toThrowError(/spacing\.x8.*not a pixel dimension/);
  });

  it("refuses an unresolved alias", () => {
    expect(() =>
      formatDimensions([dimensionToken({ value: "{core.dimension.8}" })], {
        namespace: "Spacing",
      }),
    ).toThrowError(/Unresolved alias.*spacing\.x8/);
  });
});
